### ISSUE TITLE
Should not fail all for update quick lab action

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#1024]
See https://github.com/OpenLiberty/cloud-hosted-guides/actions/runs/950538101. There was a guide fail. The rest were cancelled. Should allow the action to complete all guides.

**Comment by jakub-pomykala** [comment]
@gkwan-ibm could you please verify that this issue can now be closed.

**Comment by gkwan-ibm** [comment]
close
- it works
