### ISSUE TITLE
"null" text at the bottom of the landing page

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#169]
There is a "null" text at the bottom (under the time) of the landing page and the `Access Cloud-Hosted Guide` button at the top 
![Screen Shot 2020-12-15 at 5 06 15 PM](https://user-images.githubusercontent.com/29576299/102278473-dff2af00-3ef7-11eb-9672-08907cc5edd7.png)

but in staging SN the button at the bottom
![Screen Shot 2020-12-15 at 5 06 47 PM](https://user-images.githubusercontent.com/29576299/102278513-f3057f00-3ef7-11eb-8023-53581a8b36d0.png)

**Comment by jamiecoleman92** [comment]
This is the bug I mentioned in the scrum @gkwan-ibm when you are logged out. We have a fix it just needs to be implemented.

**Comment by jamiecoleman92** [comment]
This issue has now been resolved so I am closing this issue.
