### ISSUE TITLE
Should not use austin0 for Github login

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#170]
When use Github login, I found "Open Liberty SkillsNetwork by austin0". Should not use austin0.

![Screen Shot 2020-12-15 at 10 21 09 AM](https://user-images.githubusercontent.com/29576299/102234746-98e8c780-3ebf-11eb-9623-791d409d8155.png)

**Comment by austin0** [comment]
This has been corrected and the OAuth App is now owned by the OpenLiberty org.
