### ISSUE TITLE
Update the graphql-client guide landing page

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#2251]
with the following description:

GraphQL is an open source data query language. Unlike REST APIs, each POST request sent to a GraphQL service goes to a single HTTP endpoint. To learn more about GraphQL, see the [Optimizing REST queries for microservices with GraphQL](https://openliberty.io/guides/microprofile-graphql.html) guide.

You'll learn how to use the SmallRye GraphQL client’s typesafe interface to query and mutate data from multiple microservices.

**Comment by jakub-pomykala** [comment]
Staging update - verify [here](https://courses.ol-staging.skillsnetwork.site/courses/course-v1:IBM+GPXX04S5EN+v1/courseware/guided_project/guided_project/1?activate_block_id=block-v1%3AIBM%2BGPXX04S5EN%2Bv1%2Btype%40vertical%2Bblock%40guided_project_lets_do_it)

**Comment by jakub-pomykala** [comment]
Prod update -verify [here](https://courses.openliberty.skillsnetwork.site/courses/course-v1:IBM+GPXX04S5EN+v1/courseware/guided_project/guided_project/1?activate_block_id=block-v1%3AIBM%2BGPXX04S5EN%2Bv1%2Btype%40vertical%2Bblock%40guided_project_lets_do_it)

**Comment by gkwan-ibm** [comment]
close
- addressed
