### ISSUE TITLE
Remove the unnecessary link

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#2252]
Remove/hide the doubt circle link in the footer of the production landing pages

![Screen Shot 2022-11-02 at 10 57 24 AM](https://user-images.githubusercontent.com/29576299/199524038-24c66a6a-da01-423e-8687-f32913c86b44.png)

**Comment by jakub-pomykala** [comment]
Closing as this issue has been resolved.
