### ISSUE TITLE
.github/workflows/RunConverterOnAllGuides.yml not work

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#2274]
Supposedly, when create a PR for the GuideConverter, the .github/workflows/RunConverterOnAllGuides.yml will be called to generate a staging PR to confirm that the converter can convert the guides correctly. It seems not work.

**Comment by jakub-pomykala** [comment]
Converter repo PR triggers the action but no changes in any of the guides.
