### ISSUE TITLE
Sync the actions from the staging and prod

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#2345]
- some artifacts in staging only
  + add them to prod 
- some artifacts in prod only (less cases)
  + add them to staging
- combine some artifacts, e.g. labMirror.yml to mirror.yml
- some artifacts in both branches but not in sync
  + sync them

**Comment by jakub-pomykala** [comment]
https://github.com/OpenLiberty/cloud-hosted-guides/pull/2351 and https://github.com/OpenLiberty/cloud-hosted-guides/pull/2350

**Comment by jakub-pomykala** [comment]
PRs merged - closing issue
