### ISSUE TITLE
too many branches

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#2346]
remove the generated temporary branch after PR is merged

**Comment by jakub-pomykala** [comment]
Changed settings to automatically remove head branch post merge. 

<img width="899" alt="Screenshot 2023-01-17 at 10 52 03" src="https://user-images.githubusercontent.com/56261244/212880482-739b9a04-ee3c-4e77-a767-bd58fda65670.png">

**Comment by jakub-pomykala** [comment]
If a PR is merged the branch is deleted - but if needed it can be restored with the `restore branch` button which will appear in the PR

Example:

<img width="943" alt="Screenshot 2023-01-18 at 13 56 19" src="https://user-images.githubusercontent.com/56261244/213189984-9d92171e-2809-40c2-bb22-d5bcdedc5878.png">


Also, it will say that the branch is deleted by the person who has merged the PR but it is in fact done automatically.
