### ISSUE TITLE
Create cloud-hosted-guide-jakarta-websocket

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#2355]
- [x] create a guided-project
  - [x] quicklab
  - [x] gitlab
- [x] create landing page
- [x] update GuideConverter
   - [x] [version-history-start-date.properties](https://github.com/OpenLiberty/cloud-hosted-guide-converter/blob/main/version-history-start-date.properties)
- [x] create`.github/workflows/triggerConversion.yml`  at the [guide-jakarta-websocket](https://github.com/openliberty/guide-jakarta-websocket)
- [x] trigger the conversion for staging to generate PR `#pppp`
- [x] update the PR `#pppp`
  - [x]  copy all files from `lab-nnnn-instruction` branch except README.MD and cloud-hosted-guide-jakarta-websocket.md
  - [x]  use our own cloud-hosted-guides/instructions/cloud-hosted-guide-jakarta-websocket/lab/cloud-hosted-guide-jakarta-websocket.md
- [x] update the staging [labMirror.yml](https://github.com/OpenLiberty/cloud-hosted-guides/blob/staging/.github/workflows/labMirror.yml)
- [ ] test and fix the guide by SN Author IDE
- [x] get SN approval
- [ ] install course to the OL SN staging portal
- [ ] install course to the OL SN prod portal
- [x] update the `mirror.yml` at
  - [x] [staging](https://github.com/OpenLiberty/cloud-hosted-guides/blob/staging/.github/workflows/mirror.yml) 
  - [x] [prod](https://github.com/OpenLiberty/cloud-hosted-guides/blob/prod/.github/workflows/mirror.yml)

**Comment by gkwan-ibm** [comment]
blocking by https://github.ibm.com/skills-network/labs/issues/1682

**Comment by jakub-pomykala** [comment]
https://github.com/OpenLiberty/cloud-hosted-guide-converter/pull/188 - [version-history-start-date.properties](https://github.com/OpenLiberty/cloud-hosted-guide-converter/blob/main/version-history-start-date.properties) PR

**Comment by jakub-pomykala** [comment]
`./github/workflows/triggerConversion.yml` already exists at - https://github.com/OpenLiberty/guide-jakarta-websocket/blob/prod/.github/workflows/triggerConversion.yml

**Comment by jakub-pomykala** [comment]
Already within `labMirror.yml` - https://github.com/OpenLiberty/cloud-hosted-guides/blob/staging/.github/workflows/labMirror.yml

**Comment by gkwan-ibm** [comment]
- test failed on SNL
- blocked by https://github.ibm.com/skills-network/labs/issues/1682

**Comment by gkwan-ibm** [comment]
close
- SN does not support websocket connection
