### ISSUE TITLE
Invalid markdown instructions

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/quick-labs#243]
Accessing tutorial catalogue at https://ide.skillsnetwork.site/open-liberty-tutorial-catalogue I try to open a module and receive the following error in the Open Liberty Masterclass Modules

```
You tried to start a QuickLab with invalid markdown instructions. Please contact the QuickLab author to let them know their QuickLab is broken.
```

Encountered on [Module 1 (Build)](https://labs.cognitiveclass.ai/tools/theiadocker/?md_instructions_url=https://raw.githubusercontent.com/OpenLiberty/quick-labs/master/instructions/openliberty-masterclass/module-1.md) and [Module 2 (Dev Mode)](https://labs.cognitiveclass.ai/tools/theiadocker/?md_instructions_url=https://raw.githubusercontent.com/OpenLiberty/quick-labs/master/instructions/openliberty-masterclass/module-2.md) and [Module 3 (Application API)](https://labs.cognitiveclass.ai/tools/theiadocker/?md_instructions_url=https://raw.githubusercontent.com/OpenLiberty/quick-labs/master/instructions/openliberty-masterclass/module-3.md), have not checked other modules or categories yet. 

Accessed in Firefox on Windows 10

**Comment by jakub-pomykala** [comment]
@AustinSeto the links you have posted, where did you get them from? We have never seen them before. All the masterclasses can be found [here](https://ide.skillsnetwork.site/open-liberty-workshop)

**Comment by jakub-pomykala** [comment]
This issue has been found in one of the masterclasses. All the masterclasses should now be fully functional. Closing issue.
