### ISSUE TITLE
JS code in OpenLiberty login page is running on a setTimeOut()

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/quick-labs#333]
The only way the JS is always running is when it is running on a `setTimeOut()`. This has to be changed ASAP as it could cause problems for users in the future. The reason why it is using `setTimeOut()` is because `document.addEventListener("DOMContentLoaded", function()` nor `window.addEventListener("load", function()` did not work and caused the JS to load before the HTML/window finished loading

**Comment by jamiecoleman92** [comment]
We no longer use JS so this issue is now resolved.
