### ISSUE TITLE
Login page need more information

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#341]
Implement the new design as
![Screen Shot 2021-02-22 at 3 36 54 PM](https://user-images.githubusercontent.com/29576299/108767059-eb7bdb00-7523-11eb-8612-e0fbabe6f7b9.png)

**Comment by gkwan-ibm** [comment]
@yeekangc @jamiecoleman92 @jakub-pomykala @austin0

**Comment by yeekangc** [comment]
We need to review the whole login flow -- including alternate flows like what is noted in #344 -- to ensure that the users are clear as to what is needed and not.

**Comment by gkwan-ibm** [comment]
The login page was prototyped and need to polish the following:
- [x] give some space at the right of the sign in buttons. This problem only occurs at Firefox
  - ![Screen Shot 2021-03-08 at 9 04 13 AM](https://user-images.githubusercontent.com/29576299/110854233-a7f2d200-8282-11eb-9992-24af1b5bb74d.png)
- [x] the "Gitter for Open Liberty" and the "Groups.io" links at the bottom should open the url on new tab
- [x] The OL brand should link to home page or https://openliberty.io/? If Home page, need to address #584 
- [x] "Privacy Notice" at the "By signing in,..." paragraph should have a link to https://www.ibm.com/privacy and open on a new tab

**Comment by gkwan-ibm** [comment]
The page was reviewed by ID #716

**Comment by austin0** [comment]
Closing as pages have been updated.
