### ISSUE TITLE
The term should be consistent 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#347]
The following terms are used in different pages. 
- Open Liberty SkillsNetwork (in login page, github signin page)
- Open Liberty Skills Network (in login page)
- skillsnetwork.site (google signin page)
- Open Liberty Skills Network Portal (logout page, home page)
- Open Liberty Hands On (SN account page)

Need to be consistent

**Comment by jakub-pomykala** [comment]
Changed the welcome/home page and confirmed with @austin0 that that was the last one to be changed
