### ISSUE TITLE
Feedback for kubernetes-intro guide

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#393]
- **Starting and preparing your cluster for deployment**
  - [ ] `minikube start` not work
    - Does SN lab support minikube or DockerDesktop?

**Comment by AustinSeto** [comment]
Addressing with https://github.com/OpenLiberty/guide-kubernetes-intro/pull/166, skills network will not use Minikube

**Comment by gkwan-ibm** [comment]
close
- addressed by OpenLiberty/guide-kubernetes-intro#166
