### ISSUE TITLE
Enhance the create account page

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#447]
Implement the new design of the create account page as following:
![Screen Shot 2021-02-22 at 3 39 19 PM](https://user-images.githubusercontent.com/29576299/108767230-2ed64980-7524-11eb-9e8c-2388e6405e0f.png)

**Comment by gkwan-ibm** [comment]
The create account page was prototyped and need to polish the following:
- [x] give some space at the right of the sign in buttons (the problem similar to following screenshot). This problem only occurs at Firefox
  - ![Screen Shot 2021-03-08 at 9 04 13 AM](https://user-images.githubusercontent.com/29576299/110854233-a7f2d200-8282-11eb-9992-24af1b5bb74d.png)
- [ ] May the `(required!)`  be black not be red or even no need to show because looks too complex with the red message below the text box
  - ![Screen Shot 2021-03-08 at 9 27 38 AM](https://user-images.githubusercontent.com/29576299/110854898-9f4ecb80-8283-11eb-9935-5ef57053c3e5.png)
- [x] "Privacy Notice" at the "By signing in,..." paragraph should have a link to https://www.ibm.com/privacy and open on a new tab
- [x] After "Account activation is not required.", add "If the provider cannot provide your name and email to the IBM Developer Skill Network, you will be asked to provide them, and an account activation will be required."

**Comment by gkwan-ibm** [comment]
The page was reviewed by ID #716

**Comment by austin0** [comment]
Page has been updated and reviewed again, closing.
