### ISSUE TITLE
Landing and password recovery pages

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#448]
Both Landing and password recovery pages should look likes as:

![Screen Shot 2021-03-24 at 3 49 02 PM](https://user-images.githubusercontent.com/29576299/112374482-8a792b80-8cb8-11eb-950b-b0516dde6bf8.png)

![Screen Shot 2021-02-22 at 3 48 09 PM](https://user-images.githubusercontent.com/29576299/108768266-701b2900-7525-11eb-9323-e322e7b40ad3.png)

**Comment by jakub-pomykala** [comment]
Once Liquid themes is fully functional we will be able to change both the header and the footer. However, tested themes this morning and still not working

**Comment by jakub-pomykala** [comment]
Liquid theme is now functional. I have implemented the two logos. Just waiting on some help in regards to the userdrop down menu which has been pushed out of the header due to the two logos

**Comment by jakub-pomykala** [comment]
Header is now fully functional.

**Comment by jakub-pomykala** [comment]
Footer now been updated aswell. I think after pushing new theme to prod we should be able to close issue

**Comment by gkwan-ibm** [comment]
close
- implemented the design in the staging and prod SN
