### ISSUE TITLE
Create the landing pages for the 3rd set of guides

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#449]
- [x] microprofile-istio-retry-fallback
- [x] microprofile-jwt
- [x] microprofile-metrics
- [x] microprofile-openapi
- [x] microprofile-reactive-messaging-acknowledgment
- [x] microprofile-reactive-messaging-rest-integration
- [x] microprofile-rest-client-async

**Comment by austin0** [comment]
microprofile-istio-retry-fallback
--------------
Prod: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-istio-retry-fallback

Staging: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-istio-retry-fallback-staging

microprofile-jwt
--------------
Prod: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-jwt

Staging: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-jwt-staging

microprofile-metrics
--------------
Prod: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-metrics

Staging: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-metrics-staging

microprofile-openapi
--------------
Prod: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-openapi

Staging: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-openapi-staging

microprofile-reactive-messaging-acknowledgment
--------------
Prod: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-reactive-messaging-acknowledgment

Staging: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-reactive-messaging-acknowledgment-staging

microprofile-reactive-messaging-rest-integration
--------------
Prod: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-reactive-messaging-rest-integration

Staging: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-reactive-messaging-rest-integration-staging

microprofile-rest-client-async
--------------
Prod: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-rest-client-async

Staging: https://openliberty.skillsnetwork.site/quicklab/cloud-hosted-guide-microprofile-rest-client-async-staging
