### ISSUE TITLE
New terminal output example for starting liberty in dev mode.

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/quick-labs#451]
We have implemented a manual fix for the output example of terminal when user runs:
```
mvn liberty:dev
```

Previously the output example was
```
The defaultServer server is ready to run a smarter planet.
```

But now the output example is:
```
**********************************************************
*    Liberty is running in dev mode.
```

**Comment by gkwan-ibm** [comment]
close
- all static guides were updated and the cloud-hosted guides should be picked up
