### ISSUE TITLE
Package issue in cloud-hosted-guides

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/quick-labs#453]
In some cases, after a user clones and opens the guide in the IDE they can see loads of red files with an warming/error of "Incorrect Package Name". 

e.g. 
This is the issue:
![Screenshot 2021-02-23 at 15 50 53](https://user-images.githubusercontent.com/56261244/108869468-2565e380-75ef-11eb-9b57-53308ad472a0.png)

This is what the issue causes:
![Screenshot 2021-02-23 at 15 50 57](https://user-images.githubusercontent.com/56261244/108869473-25fe7a00-75ef-11eb-9e07-a58e258ddce0.png)

Because of this users may think that their code is broken.

**Comment by jamiecoleman92** [comment]
This has caused attendees of workshops to think their code is broken and without me there to tell them it is a known bug they may not finish the guide so this should be fixed asap. I think it is most likely something the SN team will need to fix @gkwan-ibm.

**Comment by gkwan-ibm** [comment]
I doubt it can be fixed by in the lab. Of course, we can ask SN team input.
We can also consider to ask users to close and reopen the workspace to the start directory 
or study how to add source path into the IDE

**Comment by jakub-pomykala** [comment]
https://github.ibm.com/skills-network/portals/issues/2033 Issue on the SN backlog

**Comment by gkwan-ibm** [comment]
temporary workaround to ask users to logout the quicklab, but it is performance issue if do logout

@jakub-pomykala can you ask how to clean the env without logout as a temp workaround?

**Comment by jakub-pomykala** [comment]
Asked. Waiting for reply.

**Comment by jakub-pomykala** [comment]
To clean the env without logging out users can use `exec bash`

**Comment by jakub-pomykala** [comment]
Cannot reproduce anymore.

**Comment by gkwan-ibm** [comment]
Let monitor this problem longer by different people before to close it

**Comment by gkwan-ibm** [comment]
close
- no more report for this issue
