### ISSUE TITLE
Step 7 in Reactive microservices with MicroProfile Reactive Messaging curl command takes a long time

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/quick-labs#454]
The curl command in step 7 takes a while to run. We should add a text to the static guide which will let users know that this command will take a while to run.

**Comment by gkwan-ibm** [comment]
may need to ask users to run the /health  api to determine the readiness

**Comment by gkwan-ibm** [comment]
close
- issue was fixed
