### ISSUE TITLE
Feedback for Consuming RESTful services using the reactive JAX-RS client lab

### ISSUE THREAD

**Issue by GraceJansen** [OpenLiberty/quick-labs#53]
What you'll learn
--------------------
- [x] Not formatted correctly --> Youll first look at the supplied client application that uses the JAX-RS default **CompletionStage**-based provider. Then, youll mo --> should just be the completionstage that's formatted differently, all the rest should be normal text

- [x] Remove pre-req section, not needed for snl

--------
Creating a web client using the default JAX-RS API
---------

- [x] this needs to be removed --> InventoryClient.java

- [x] Needs to be used, not use --> JAX-RS provides a default reactive provider that you can use to create

- [x] Missing a cd start command before first touch command to Create the InventoryClient interface.

- [x] Codeblock for InventoryClient interface has gone very wrong!

<img width="492" alt="Screenshot 2020-09-16 at 11 45 32" src="https://user-images.githubusercontent.com/32962135/93327380-23af1d00-f812-11ea-839f-cb0a68ba13ad.png">

- [x] All the codeblocks and normal text after this seem to have been reversed and are all wrong for the remainder of this section.

- [x] None of the sections have been separated out into new tabs in SNL following this

**Comment by jakub-pomykala** [comment]
Changes done and tested.
