### ISSUE TITLE
Improve the refresh infrastructure/mechanism

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#577]
Every time commit a PR, all guides will be triggered to refresh. It slows down the SN. 
Need to improve the refresh infrastructure/mechanism
- when merge a PR, only refresh 1 guide in SN, now refresh all guides
- PR not for guide, should not refresh SN

**Comment by austin0** [comment]
The current infrastructure will only mirror the content of `cloud-hosted-guides` if it differs to the version stored on the Skills Network repositories.

I will look at updating the mirror scripts to only run when changes are made to guides (as opposed to workflows/example files).

**Comment by austin0** [comment]
Passing this off to Ryan and Jakub, should be easy to make it only run on changes to the guides (`on: ... instructions/*`). Will need a bit more work to make it only attempt to mirror the guide that had changes made to it.

**Comment by gkwan-ibm** [comment]
close
- the mirror actions are working fine for both staging and prod
