### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#584]
Need to discuss and design the home page

**Comment by gkwan-ibm** [comment]
close
- implemented the home page with a simple message

**Comment by jamiecoleman92** [comment]
The home page and welcome pages need to be changed as they currently contain an old workshop. Not only do we need a new title but we need a link or a message explaining how to access the content via either a link or by sending the user back to the openliberty.io site.

**Comment by austin0** [comment]
Home page has been updated on staging: https://ol-staging.skillsnetwork.site/

Pending ID review then will be made live on production.

**Comment by gkwan-ibm** [comment]
close
- ID reviewed 
- backup at Portal-Assets/pages/home-page.md
- PR #868, #869
