### ISSUE TITLE
microprofile-jwt feedback

### ISSUE THREAD

**Issue by tt-le** [OpenLiberty/quick-labs#592]
## Step 3

- [ ] The formatting of the table is a bit off. Maybe put spaces between `username` `roles` `password`
<img width="705" alt="Screen Shot 2021-03-12 at 4 23 34 PM" src="https://user-images.githubusercontent.com/44335153/111000029-4d737780-834f-11eb-90d6-d62514668363.png">

## Step 7
- [ ] <img width="1111" alt="Screen Shot 2021-03-15 at 1 47 34 PM" src="https://user-images.githubusercontent.com/44335153/111197567-01b20f80-8595-11eb-97f4-299a45309b34.png">, getting this issue

## Step ..
Could complete the lab

## Overall

- [x] When creating new files, I found it easier to command+click rather then following `select File > Open > guide-microprofile-jwt/start/frontend/src/main/java/io/openliberty/guides/frontend/ApplicationBean.java` 
<img width="731" alt="Screen Shot 2021-03-15 at 1 37 54 PM" src="https://user-images.githubusercontent.com/44335153/111196449-a7fd1580-8593-11eb-9a98-ba506687dc88.png">

- [x] Alternatively, when doing it locally on VSCode, you can do `code -r guide-microprofile-jwt/start/frontend/src/main/java/io/openliberty/guides/frontend/ApplicationBean.java` and it will open that file directly within the current instance of VSCode. To do this, we would need to add vscode to the path.

**Comment by gkwan-ibm** [comment]
- step 3 is cosmetic, not fix in this cycle, and hope it will be addressed when implement the static guide look
- cannot reproduce step 7
-  VSCode in the lab does not have `code` command and `Cmd + click` not good enough

**Comment by jamiecoleman92** [comment]
This guide is now live with no reported issues.
