### ISSUE TITLE
Gilbert's review feedback

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#70]
- GuideConverter.java
  - Need license comment in the java file
  - Better not hard code the string but read the adoc files from the guides-common repository
    - generic code to read adoc file 
  - `writeToFile()` is not efficient to open, write, and close the .md file. Either
    - write the content to a string buffer/stream, at end write the string buffer/stream to the .md file
    - or open the file stream at the beginning, and close at the end
  - in `getMD(String guideName)`, look like the "temp.adoc" is just opened and closed. Any reason?
  - in `codeSnippet(String path, String guideName)`, look like the "temp.adoc" is just opened and not closed. Any reason?
- actions.yaml
  - README.md is removed before running the GuideConverter. In case, GuideConverter fail, will README.md be removed and PR still created?
- Does the action directly update the master? If yes, need to make sure the automation won't screw up the master, especailly in failure, although it is possible to revert the PR. (i.e. if failure, no update)

**Comment by jakub-pomykala** [comment]
Closing as GuideConverter has been changed.
