### ISSUE TITLE
Register and Login pages: ID review

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/quick-labs#716]
Suggested edits for register and Login pages:

## Register page

We will send you an account activation email. You can sign into the cloud-hosted guides next time, after you activate your account through that email. 
--->
When you create an account, we send you an account activation email. You can sign in to the cloud-hosted guides after you activate your account through that email. 

If the provider cannot provide your name and email to the IBM Developer Skill Network, you will be asked to create a regular IBM Developer Skills Network account.
--->
If the provider cannot provide your name and email to the IBM Developer Skill Network, you must create a regular IBM Developer Skills Network account.
OR
If the provider cannot provide your name and email to the IBM Developer Skill Network, we ask that you create a regular IBM Developer Skills Network account.

I am at least sixteen years of age. 
--->
I am at least 16 years of age.

## Login page
The OpenLiberty cloud-hosted guides 
--->
The Open Liberty cloud-hosted guides 

 You can sign in with IBM Development Skills Network account or one of the following single sign-on providers.
--->
 You can sign in with an IBM Development Skills Network account or through one of the following single sign-on providers.

I am at least sixteen years of age. 
--->
I am at least 16 years of age.

**Comment by gkwan-ibm** [comment]
close
- both pages were updated
