### ISSUE TITLE
Update and convert guide-reactive-rest-client

### ISSUE THREAD

**Issue by austin0** [OpenLiberty/quick-labs#73]
The lab for guide-reactive-rest-client seems to be quite out out of date and has errors that are fixed in the current version, it also seems to have been converted with an old version of the tool so could use a refresh to fix a number of syntax errors.

Link to guide: https://github.com/openliberty/guide-reactive-rest-client

@jakub-pomykala can this be a situation to test the automation bot?

**Comment by jakub-pomykala** [comment]
Atm the GuideConverter is going under some major surgery. The automation won't be tested for a while. If it's very out of date might be worth updating it manually for now. @jamiecoleman92

**Comment by austin0** [comment]
https://github.com/OpenLiberty/quick-labs/pull/74 opened to fix identified issues.
