### ISSUE TITLE
Set up more development quicklabs

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#737]
create more development quicklabs as https://github.com/OpenLiberty/cloud-hosted-guides/blob/staging/instructions/cloud-hosted-draft-guide-development/instructions.md
- include to update the github action(s)

e.g. `cloud-hosted-draft-guide-development-1`, `cloud-hosted-draft-guide-development-2`, `cloud-hosted-draft-guide-development-3`

**Comment by jakub-pomykala** [comment]
We now have 4 development quicklabs available
