### ISSUE TITLE
Can logout from the landing page redirect back to the openliberty.io?

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#814]
When users logout from landing page, SN should redirect them back to the openliberty.io/guides

**Comment by jakub-pomykala** [comment]
Done

**Comment by gkwan-ibm** [comment]
@jakub-pomykala 
redirect to https://openliberty.io/guides not https://openliberty.io

**Comment by jakub-pomykala** [comment]
Sorry closed the issue to quick, it is done on staging anyway, have not moved over to prod

**Comment by jakub-pomykala** [comment]
Now points to https://openliberty.io/guides

**Comment by jakub-pomykala** [comment]
Need to update prod lms to enable on production

**Comment by gkwan-ibm** [comment]
close
- problem was resolved
