### ISSUE TITLE
Document the set up of all SSO

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/quick-labs#830]
Create a document for the set up of all SSO. 
- [x] Github
  - who can update the OAuth app?
  - how to configure the SN portal?
- [x] Google
   - gmail id and who owns password
   - how to set up in [Google API Console](https://console.developers.google.com/)?
   - how to configure the SN portal?
- [x] IBM ID
   - whatever 
   - how to configure the SN portal?
- [x] LinkedIn
   - whatever 
   - how to configure the SN portal?

**Comment by austin0** [comment]
SSO documentation in progress: https://ibm.ent.box.com/notes/802623150292

**Comment by austin0** [comment]
Documentation now covers all the current SSO providers with links to associated documentation. It also lists the people with access to make changes to the current SSO applications.
