### ISSUE TITLE
Add feedback faces into the guides

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/quick-labs#956]
Add the feedback faces from openliberty.io to the end of the cloud-hosted-guides section. 

<img width="489" alt="Screenshot 2021-05-28 at 10 56 40" src="https://user-images.githubusercontent.com/56261244/119966607-63cebe00-bfa3-11eb-994b-84575edd318a.png">

These will have to be connected using the GA (Google analytics) and will have to contain JS script to be reactive.

Another possible way is to have the face when clicked send a POST request to the google analytics.

**Comment by gkwan-ibm** [comment]
close
- add Give us feedback link to the last step
