### ISSUE TITLE
Use the same favicon for SNL site as openliberty.io

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/quick-labs#994]
Currently, our SNL portal uses the round favicon.  Use the same squarish favicon instead to be consistent with openliberty.io.

<img width="187" alt="Screen Shot 2021-06-03 at 11 10 15 AM" src="https://user-images.githubusercontent.com/4803104/120668291-53638b00-c45c-11eb-83f5-9e76f1a2a947.png">

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by jakub-pomykala** [comment]
Updated on 14th of June 2021.

**Comment by jakub-pomykala** [comment]
@yeekangc if you could please verify that would be great.

**Comment by yeekangc** [comment]
LGTM.  Thanks, @jakub-pomykala.
